export const GROUP_ACTION_TYPE = {
    ADD_GROUPS: "ADD_GROUPS",
    UPDATE_GROUPS: "UPDATE_GROUPS",
    GET_GROUPS: "GET_GROUPS",
    ADD_MEMBERS: "ADD_MEMBERS",
    UPDATE_DETAILS:"UPDATE_DETAILS"
}