export const LINK_ACTION_TYPE = {
    UPDATE_GROUP_ACCESS: "UPDATE_GROUP_ACCESS",
    UPDATE_MEMBER_ACCESS: "UPDATE_MEMBER_ACCESS",
    ADD_GROUP: "ADD_GROUP",
    ADD_MEMBER: "ADD_MEMBER",
    REMOVE_GROUP: "REMOVE_GROUP",
    REMOVE_MEMBER: "REMOVE_MEMBER",
    GET_ACCESS_DETAILS: "GET_ACCESS_DETAILS",
    GET_MEMBER_ACCESS_DETAILS: "GET_MEMBER_ACCESS_DETAILS",
    GET_GROUP_ACCESS_DETAILS: "GET_GROUP_ACCESS_DETAILS",
    ADD_ACCESS_DETAILS: "ADD_ACCESS_DETAILS"
}